"""add_columns_to_automobiles_and_trips

Revision ID: 529bd3318f52
Revises: be3550d1e769
Create Date: 2025-12-31 17:54:25.689206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529bd3318f52'
down_revision: Union[str, Sequence[str], None] = 'be3550d1e769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automobiles', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('automobiles', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'status')
    op.drop_column('automobiles', 'is_active')
    op.drop_column('automobiles', 'year')
    # ### end Alembic commands ###
