"""automobile add metadata jsonb

Revision ID: 8b4a29d8f364
Revises: ef0e9e0bceeb
Create Date: 2025-12-31 20:11:26.244374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b4a29d8f364'
down_revision: Union[str, Sequence[str], None] = 'ef0e9e0bceeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automobiles', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automobiles', 'meta_data')
    # ### end Alembic commands ###
