"""add_index_to_car_and_trip

Revision ID: ef0e9e0bceeb
Revises: 529bd3318f52
Create Date: 2025-12-31 18:00:07.145079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0e9e0bceeb'
down_revision: Union[str, Sequence[str], None] = '529bd3318f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('automobiles_license_plate_key'), 'automobiles', type_='unique')
    op.create_index(op.f('ix_automobiles_license_plate'), 'automobiles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_trips_auto_id'), 'trips', ['auto_id'], unique=False)
    op.create_index(op.f('ix_trips_departure_date'), 'trips', ['departure_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_departure_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_auto_id'), table_name='trips')
    op.drop_index(op.f('ix_automobiles_license_plate'), table_name='automobiles')
    op.create_unique_constraint(op.f('automobiles_license_plate_key'), 'automobiles', ['license_plate'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
